# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dtools < Formula
  desc ""
  homepage "https://github.com/Solidsilver/homebrew-tools"
  version "1.0.16"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Solidsilver/homebrew-tools/releases/download/v1.0.16/homebrew-tools_Darwin_arm64.tar.gz"
      sha256 "dbb92facd8aa8ae47a483c62d3985c8b19236d9efc9e9bf9e6ae654be9f9d916"

      def install
        bin.install "amu"
        bin.install "env-templator"
        bin.install "vcip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Solidsilver/homebrew-tools/releases/download/v1.0.16/homebrew-tools_Darwin_x86_64.tar.gz"
      sha256 "2df5455fcfe9c7f02c57572979fef4bd2d746d0d2a2b3aa2bc2db76399ca3766"

      def install
        bin.install "amu"
        bin.install "env-templator"
        bin.install "vcip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Solidsilver/homebrew-tools/releases/download/v1.0.16/homebrew-tools_Linux_arm64.tar.gz"
      sha256 "8a0cc477dc491e97948e9ab24fbce892ac1fe541e301b11d5249ae01dc5c9bbc"

      def install
        bin.install "amu"
        bin.install "env-templator"
        bin.install "vcip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Solidsilver/homebrew-tools/releases/download/v1.0.16/homebrew-tools_Linux_x86_64.tar.gz"
      sha256 "15fe3098148cd1bc2fc1fcb5ad50a4033fcf53b8fe648fba8168b6eb53fedf06"

      def install
        bin.install "amu"
        bin.install "env-templator"
        bin.install "vcip"
      end
    end
  end
end
