# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dtools < Formula
  desc ""
  homepage "https://github.com/Solidsilver/homebrew-tools"
  version "1.0.16"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Solidsilver/homebrew-tools/releases/download/v1.0.16/homebrew-tools_Darwin_arm64.tar.gz"
      sha256 "f428672118cdd7acc04867126ab7315c87acbdaae54a7801741a66bd8b630e6e"

      def install
        bin.install "amu"
        bin.install "env-templator"
        bin.install "vcip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Solidsilver/homebrew-tools/releases/download/v1.0.16/homebrew-tools_Darwin_x86_64.tar.gz"
      sha256 "15b17cb4e1d8d569005c4d200468a093b021ee6de693fdf66ab6def31b23fe4c"

      def install
        bin.install "amu"
        bin.install "env-templator"
        bin.install "vcip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Solidsilver/homebrew-tools/releases/download/v1.0.16/homebrew-tools_Linux_arm64.tar.gz"
      sha256 "a763d9ab0ed9708971db958e7202b6b6ecb6736171dc52841f8f5bcf758d3f37"

      def install
        bin.install "amu"
        bin.install "env-templator"
        bin.install "vcip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Solidsilver/homebrew-tools/releases/download/v1.0.16/homebrew-tools_Linux_x86_64.tar.gz"
      sha256 "b7f19ebaa33c3af20d5c0734ef8c30ecd71d6336de7f1a8a7dbadd0ea6947625"

      def install
        bin.install "amu"
        bin.install "env-templator"
        bin.install "vcip"
      end
    end
  end
end
