# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dtools < Formula
  desc ""
  homepage "https://github.com/Solidsilver/homebrew-tools"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Solidsilver/homebrew-tools/releases/download/v1.1.0/homebrew-tools_Darwin_arm64.tar.gz"
      sha256 "af8d6ee3bab9a09ef47aae7dc15f490a9297dd352f3c012319f34767574aca60"

      def install
        bin.install "amu"
        bin.install "env-templator"
        bin.install "vcip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Solidsilver/homebrew-tools/releases/download/v1.1.0/homebrew-tools_Darwin_x86_64.tar.gz"
      sha256 "5cc8995cd97949eb524310cf3569028122e1d4fa8a98359788176d0ceecb04ea"

      def install
        bin.install "amu"
        bin.install "env-templator"
        bin.install "vcip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Solidsilver/homebrew-tools/releases/download/v1.1.0/homebrew-tools_Linux_arm64.tar.gz"
      sha256 "259272ccc009c2c6f1a29cd7262194d774bff1865cd22cf7f9ab5a8d28a073fe"

      def install
        bin.install "amu"
        bin.install "env-templator"
        bin.install "vcip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Solidsilver/homebrew-tools/releases/download/v1.1.0/homebrew-tools_Linux_x86_64.tar.gz"
      sha256 "2b66c6b634f89750d25dc3499c8908cf7963221153d42bf6483b318b4d08e8f7"

      def install
        bin.install "amu"
        bin.install "env-templator"
        bin.install "vcip"
      end
    end
  end
end
