# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EnvTemplator < Formula
  desc ""
  homepage "https://github.com/Solidsilver/homebrew-tools"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Solidsilver/go-fs-tools/releases/download/v0.1.4/go-fs-tools_Darwin_arm64.tar.gz"
      sha256 "427a86f8d9a4565cb60b1f0a561bf2583c0060648744361f92064ad33e86af6e"

      def install
        bin.install "env-templator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Solidsilver/go-fs-tools/releases/download/v0.1.4/go-fs-tools_Darwin_x86_64.tar.gz"
      sha256 "563fda7347a91abb1eb6e8984d02b6e5a48abcbd0c86938db7f9307661e796e4"

      def install
        bin.install "env-templator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Solidsilver/go-fs-tools/releases/download/v0.1.4/go-fs-tools_Linux_x86_64.tar.gz"
      sha256 "8e5577c9f69f7b199a2a2e758a596b37b7800c0381eafc9df7c2fd75a2bbc7f9"

      def install
        bin.install "env-templator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Solidsilver/go-fs-tools/releases/download/v0.1.4/go-fs-tools_Linux_arm64.tar.gz"
      sha256 "afc908906a070b8739d2dca648121d761910c30551958afbb88c8f73f88f9a2e"

      def install
        bin.install "env-templator"
      end
    end
  end
end
